spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    driver-class-name: org.h2.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create-drop
    Properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug

